"""add checkout address, maps url, and task summary

Revision ID: 043853e78be8
Revises: a7d0527bf60b
Create Date: 2026-07-30 16:29:39.207993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043853e78be8'
down_revision: Union[str, None] = 'a7d0527bf60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('check_out_address', sa.String(length=500), nullable=True))
    op.add_column('attendance', sa.Column('check_out_google_maps_url', sa.String(length=500), nullable=True))
    op.add_column('attendance', sa.Column('checkout_task_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'checkout_task_summary')
    op.drop_column('attendance', 'check_out_google_maps_url')
    op.drop_column('attendance', 'check_out_address')
    # ### end Alembic commands ###
